version: '3.5'

services:
    app:
        image: node:lts-alpine
        volumes:
            - ./:/app
        working_dir: /app
        ports:
            - 8080:8080
        command: npm run dev
        tty: true